-- Replace EventStatus enum with approval workflow statuses.
-- DRAFT/PLANNED → PENDING_EXECUTOR_APPROVAL; CONFIRMED → APPROVED_BY_EXECUTOR.

CREATE TYPE "EventStatus_new" AS ENUM (
  'PENDING_EXECUTOR_APPROVAL',
  'PENDING_CUSTOMER_APPROVAL',
  'APPROVED_BY_EXECUTOR',
  'APPROVED_BY_CUSTOMER',
  'IN_PROGRESS',
  'DONE',
  'CANCELLED',
  'DELETED'
);

ALTER TABLE "MaintenanceEvent"
  ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "MaintenanceEvent"
  ALTER COLUMN "status" TYPE "EventStatus_new"
  USING (
    CASE "status"::text
      WHEN 'DRAFT' THEN 'PENDING_EXECUTOR_APPROVAL'
      WHEN 'PLANNED' THEN 'PENDING_EXECUTOR_APPROVAL'
      WHEN 'CONFIRMED' THEN 'APPROVED_BY_EXECUTOR'
      WHEN 'IN_PROGRESS' THEN 'IN_PROGRESS'
      WHEN 'DONE' THEN 'DONE'
      WHEN 'CANCELLED' THEN 'CANCELLED'
      WHEN 'DELETED' THEN 'DELETED'
      ELSE 'PENDING_EXECUTOR_APPROVAL'
    END::"EventStatus_new"
  );

DROP TYPE "EventStatus";

ALTER TYPE "EventStatus_new" RENAME TO "EventStatus";

ALTER TABLE "MaintenanceEvent"
  ALTER COLUMN "status" SET DEFAULT 'PENDING_EXECUTOR_APPROVAL'::"EventStatus";
