/* Generated from all_report.XLSX, sheet “Первичная таблица”. Do not edit entries manually. */
import type { PrimaryTableColumnDef } from "./types.js";

export const PRIMARY_TABLE_COLUMNS: PrimaryTableColumnDef[] = [
  {
    "key": "primary.a",
    "excelColumn": "A",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Фюзеляж",
    "path": "Идентификация и классификация / Фюзеляж",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "AircraftType.bodyType",
    "formula": null,
    "sortOrder": 1
  },
  {
    "key": "primary.b",
    "excelColumn": "B",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Год",
    "path": "Идентификация и классификация / Год",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "integer",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "IF(AI7=\"Performed\",YEAR(AM7),YEAR(Z7))",
    "sortOrder": 2
  },
  {
    "key": "primary.c",
    "excelColumn": "C",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Месяц",
    "path": "Идентификация и классификация / Месяц",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "string",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "CHOOSE(MONTH(Z7), \"Январь\", \"Февраль\", \"Март\", \"Апрель\", \"Май\", \"Июнь\", \"Июль\", \"Август\", \"Сентябрь\", \"Октябрь\", \"Ноябрь\", \"Декабрь\")",
    "sortOrder": 3
  },
  {
    "key": "primary.d",
    "excelColumn": "D",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Неделя",
    "path": "Идентификация и классификация / Неделя",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "string",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "TEXT(Z7-WEEKDAY(Z7,2)+1,\"ДД\")& \"-\" & TEXT(Z7-WEEKDAY(Z7,2)+7,\"ДД.ММ.ГГГГ\")",
    "sortOrder": 4
  },
  {
    "key": "primary.e",
    "excelColumn": "E",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Заказчик",
    "path": "Идентификация и классификация / Заказчик",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "Aircraft.operator.name",
    "formula": null,
    "sortOrder": 5
  },
  {
    "key": "primary.f",
    "excelColumn": "F",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Выполнение сторонней организацией",
    "path": "Идентификация и классификация / Выполнение сторонней организацией",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "C-check",
    "type": "boolean",
    "availability": "available",
    "source": "Hangar.isPhysical / EventPrimaryExtension.externalExecution",
    "formula": null,
    "sortOrder": 6
  },
  {
    "key": "primary.g",
    "excelColumn": "G",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Номер ВС",
    "path": "Идентификация и классификация / Номер ВС",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "Aircraft.tailNumber",
    "formula": null,
    "sortOrder": 7
  },
  {
    "key": "primary.h",
    "excelColumn": "H",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Тип ВС",
    "path": "Идентификация и классификация / Тип ВС",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "AircraftType.name",
    "formula": null,
    "sortOrder": 8
  },
  {
    "key": "primary.i",
    "excelColumn": "I",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Дата производства",
    "path": "Идентификация и классификация / Дата производства",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "date",
    "availability": "available",
    "source": "Aircraft.manufactureDate",
    "formula": null,
    "sortOrder": 9
  },
  {
    "key": "primary.j",
    "excelColumn": "J",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Лет на момент начала ПТО",
    "path": "Идентификация и классификация / Лет на момент начала ПТО",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "IFERROR(ROUND(YEARFRAC(I7,Y7),1),\" \")",
    "sortOrder": 10
  },
  {
    "key": "primary.k",
    "excelColumn": "K",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Форма ТО",
    "path": "Идентификация и классификация / Форма ТО",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "MaintenanceEvent.title",
    "formula": null,
    "sortOrder": 11
  },
  {
    "key": "primary.l",
    "excelColumn": "L",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Нормализованная форма",
    "path": "Идентификация и классификация / Нормализованная форма",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "EventType.name",
    "formula": null,
    "sortOrder": 12
  },
  {
    "key": "primary.m",
    "excelColumn": "M",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Нормализованная форма (подробно)",
    "path": "Идентификация и классификация / Нормализованная форма (подробно)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "EventPrimaryExtension.normalizedFormDetail",
    "formula": null,
    "sortOrder": 13
  },
  {
    "key": "primary.n",
    "excelColumn": "N",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Станция выполнения ТО",
    "path": "Идентификация и классификация / Станция выполнения ТО",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "Hangar.station",
    "formula": null,
    "sortOrder": 14
  },
  {
    "key": "primary.o",
    "excelColumn": "O",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Составная/одиночная фаза",
    "path": "Идентификация и классификация / Составная/одиночная фаза",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "EventPrimaryExtension.phaseKind",
    "formula": null,
    "sortOrder": 15
  },
  {
    "key": "primary.p",
    "excelColumn": "P",
    "group": "Идентификация и классификация",
    "subgroup": null,
    "label": "Слот для ТО (плановый/внеплановый)",
    "path": "Идентификация и классификация / Слот для ТО (плановый/внеплановый)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "MaintenanceEvent.planningKind",
    "formula": null,
    "sortOrder": 16
  },
  {
    "key": "primary.q",
    "excelColumn": "Q",
    "group": "Слот Заказчика (Первоначальный запрос) C-CHECK",
    "subgroup": null,
    "label": "Дата начала слота (План заказчика)",
    "path": "Слот Заказчика (Первоначальный запрос) C-CHECK / Дата начала слота (План заказчика)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "С-check",
    "type": "date",
    "availability": "available",
    "source": "EventCustomerSlot.startAt",
    "formula": null,
    "sortOrder": 17
  },
  {
    "key": "primary.r",
    "excelColumn": "R",
    "group": "Слот Заказчика (Первоначальный запрос) C-CHECK",
    "subgroup": null,
    "label": "Дата окончания слота (План заказчика)",
    "path": "Слот Заказчика (Первоначальный запрос) C-CHECK / Дата окончания слота (План заказчика)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "С-check",
    "type": "date",
    "availability": "available",
    "source": "EventCustomerSlot.endAt",
    "formula": null,
    "sortOrder": 18
  },
  {
    "key": "primary.s",
    "excelColumn": "S",
    "group": "Слот Заказчика (Первоначальный запрос) C-CHECK",
    "subgroup": null,
    "label": "D/L",
    "path": "Слот Заказчика (Первоначальный запрос) C-CHECK / D/L",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "С-check",
    "type": "string",
    "availability": "available",
    "source": "EventCustomerSlot.dlFlag",
    "formula": null,
    "sortOrder": 19
  },
  {
    "key": "primary.t",
    "excelColumn": "T",
    "group": "Слот Заказчика (Первоначальный запрос) C-CHECK",
    "subgroup": null,
    "label": "Продолжительность слота(Дни)",
    "path": "Слот Заказчика (Первоначальный запрос) C-CHECK / Продолжительность слота(Дни)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "С-check",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "R7-Q7+1",
    "sortOrder": 20
  },
  {
    "key": "primary.u",
    "excelColumn": "U",
    "group": "Слот Бюджет (Утвержденный слот) C-CHECK",
    "subgroup": null,
    "label": "Дата начала слота (План Бюджет)",
    "path": "Слот Бюджет (Утвержденный слот) C-CHECK / Дата начала слота (План Бюджет)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "С-check",
    "type": "date",
    "availability": "available",
    "source": "MaintenanceEvent.budgetStartAt",
    "formula": null,
    "sortOrder": 21
  },
  {
    "key": "primary.v",
    "excelColumn": "V",
    "group": "Слот Бюджет (Утвержденный слот) C-CHECK",
    "subgroup": null,
    "label": "Дата окончания слота (План Бюджет)",
    "path": "Слот Бюджет (Утвержденный слот) C-CHECK / Дата окончания слота (План Бюджет)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "С-check",
    "type": "date",
    "availability": "available",
    "source": "MaintenanceEvent.budgetEndAt",
    "formula": null,
    "sortOrder": 22
  },
  {
    "key": "primary.w",
    "excelColumn": "W",
    "group": "Слот Бюджет (Утвержденный слот) C-CHECK",
    "subgroup": null,
    "label": "Продолжительность слота(Дни)",
    "path": "Слот Бюджет (Утвержденный слот) C-CHECK / Продолжительность слота(Дни)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "С-check",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "V7-U7+1",
    "sortOrder": 23
  },
  {
    "key": "primary.x",
    "excelColumn": "X",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Время начала слота (План)",
    "path": "Слот План (Согласованный слот) / Время начала слота (План)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "datetime",
    "availability": "available",
    "source": "MaintenanceEvent.startAt (time)",
    "formula": null,
    "sortOrder": 24
  },
  {
    "key": "primary.y",
    "excelColumn": "Y",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Дата начала слота (План)",
    "path": "Слот План (Согласованный слот) / Дата начала слота (План)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "datetime",
    "availability": "available",
    "source": "MaintenanceEvent.startAt",
    "formula": null,
    "sortOrder": 25
  },
  {
    "key": "primary.z",
    "excelColumn": "Z",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Дата окончания слота (План)",
    "path": "Слот План (Согласованный слот) / Дата окончания слота (План)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "datetime",
    "availability": "available",
    "source": "MaintenanceEvent.endAt",
    "formula": null,
    "sortOrder": 26
  },
  {
    "key": "primary.aa",
    "excelColumn": "AA",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Время окончания слота (План)",
    "path": "Слот План (Согласованный слот) / Время окончания слота (План)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "datetime",
    "availability": "available",
    "source": "MaintenanceEvent.endAt (time)",
    "formula": null,
    "sortOrder": 27
  },
  {
    "key": "primary.ab",
    "excelColumn": "AB",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Продолжительность слота (Дни) (План)",
    "path": "Слот План (Согласованный слот) / Продолжительность слота (Дни) (План)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "Z-Y",
    "sortOrder": 28
  },
  {
    "key": "primary.ac",
    "excelColumn": "AC",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Продолжительность слота (Часы) (План)",
    "path": "Слот План (Согласованный слот) / Продолжительность слота (Часы) (План)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "(Z7+AA7)-(Y7+X7)",
    "sortOrder": 29
  },
  {
    "key": "primary.ad",
    "excelColumn": "AD",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Статус согласования",
    "path": "Слот План (Согласованный слот) / Статус согласования",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "EventPrimaryExtension.agreementStatus / status",
    "formula": null,
    "sortOrder": 30
  },
  {
    "key": "primary.ae",
    "excelColumn": "AE",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Комментарии ИТП / Специфические работы, влияющие на увеличение слота",
    "path": "Слот План (Согласованный слот) / Комментарии ИТП / Специфические работы, влияющие на увеличение слота",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "MaintenanceEvent.notes",
    "formula": null,
    "sortOrder": 31
  },
  {
    "key": "primary.af",
    "excelColumn": "AF",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Номер ангара",
    "path": "Слот План (Согласованный слот) / Номер ангара",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "Hangar.code",
    "formula": null,
    "sortOrder": 32
  },
  {
    "key": "primary.ag",
    "excelColumn": "AG",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Номер МС в ангаре",
    "path": "Слот План (Согласованный слот) / Номер МС в ангаре",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "HangarStand.code",
    "formula": null,
    "sortOrder": 33
  },
  {
    "key": "primary.ah",
    "excelColumn": "AH",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Подразделение",
    "path": "Слот План (Согласованный слот) / Подразделение",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "Workshop.name (Цех)",
    "formula": null,
    "sortOrder": 34
  },
  {
    "key": "primary.ai",
    "excelColumn": "AI",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "Статус выполнения",
    "path": "Слот План (Согласованный слот) / Статус выполнения",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "MaintenanceEvent.status",
    "formula": null,
    "sortOrder": 35
  },
  {
    "key": "primary.aj",
    "excelColumn": "AJ",
    "group": "Слот План (Согласованный слот)",
    "subgroup": null,
    "label": "II C-check (Факт)",
    "path": "Слот План (Согласованный слот) / II C-check (Факт)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "C-check",
    "type": "boolean",
    "availability": "available",
    "source": "EventPrimaryExtension.iiCCheckFact",
    "formula": null,
    "sortOrder": 36
  },
  {
    "key": "primary.ak",
    "excelColumn": "AK",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Время начала слота (Факт)",
    "path": "Слот Факт (Фактический слот) / Время начала слота (Факт)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "datetime",
    "availability": "available",
    "source": "MaintenanceEvent.actualStartAt (time)",
    "formula": null,
    "sortOrder": 37
  },
  {
    "key": "primary.al",
    "excelColumn": "AL",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Дата начала слота (Факт)",
    "path": "Слот Факт (Фактический слот) / Дата начала слота (Факт)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "datetime",
    "availability": "available",
    "source": "MaintenanceEvent.actualStartAt",
    "formula": null,
    "sortOrder": 38
  },
  {
    "key": "primary.am",
    "excelColumn": "AM",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Дата окончания слота (Факт)",
    "path": "Слот Факт (Фактический слот) / Дата окончания слота (Факт)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "datetime",
    "availability": "available",
    "source": "MaintenanceEvent.actualEndAt",
    "formula": null,
    "sortOrder": 39
  },
  {
    "key": "primary.an",
    "excelColumn": "AN",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Время окончания слота",
    "path": "Слот Факт (Фактический слот) / Время окончания слота",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "datetime",
    "availability": "available",
    "source": "MaintenanceEvent.actualEndAt (time)",
    "formula": null,
    "sortOrder": 40
  },
  {
    "key": "primary.ao",
    "excelColumn": "AO",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Продолжительность слота (Дни) (Факт)",
    "path": "Слот Факт (Фактический слот) / Продолжительность слота (Дни) (Факт)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "AM-AL",
    "sortOrder": 41
  },
  {
    "key": "primary.ap",
    "excelColumn": "AP",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Продолжительность слота (Часы) (Факт)",
    "path": "Слот Факт (Фактический слот) / Продолжительность слота (Часы) (Факт)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "(AM7+AN7)-(AL7+AK7)",
    "sortOrder": 42
  },
  {
    "key": "primary.aq",
    "excelColumn": "AQ",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Отклонение Продолжительность Дни (Факт от Бюджета)",
    "path": "Слот Факт (Фактический слот) / Отклонение Продолжительность Дни (Факт от Бюджета)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "C-check",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "W7-AO7",
    "sortOrder": 43
  },
  {
    "key": "primary.ar",
    "excelColumn": "AR",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Причина отклонения слота (От Бюджета)",
    "path": "Слот Факт (Фактический слот) / Причина отклонения слота (От Бюджета)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "C-check",
    "type": "string",
    "availability": "available",
    "source": "EventSlotDeviation.DURATION_VS_BUDGET",
    "formula": null,
    "sortOrder": 44
  },
  {
    "key": "primary.as",
    "excelColumn": "AS",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Отклонение Продолжительность Дни (Факт От согласованного плана)",
    "path": "Слот Факт (Фактический слот) / Отклонение Продолжительность Дни (Факт От согласованного плана)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "AB7-AO7",
    "sortOrder": 45
  },
  {
    "key": "primary.at",
    "excelColumn": "AT",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Отклонение Продолжительность Часы (Факт От согласованного плана)",
    "path": "Слот Факт (Фактический слот) / Отклонение Продолжительность Часы (Факт От согласованного плана)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "AC7-AP7",
    "sortOrder": 46
  },
  {
    "key": "primary.au",
    "excelColumn": "AU",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Причина продления слота (От согласованного плана)",
    "path": "Слот Факт (Фактический слот) / Причина продления слота (От согласованного плана)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "string",
    "availability": "available",
    "source": "EventSlotDeviation.DURATION_VS_PLAN",
    "formula": null,
    "sortOrder": 47
  },
  {
    "key": "primary.av",
    "excelColumn": "AV",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Смещение слота (Факт от Бюджета)",
    "path": "Слот Факт (Фактический слот) / Смещение слота (Факт от Бюджета)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "C-check",
    "type": "string",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "IF(AL7<>U7,\"Есть отклонение\",\"Нет отклонений\")",
    "sortOrder": 48
  },
  {
    "key": "primary.aw",
    "excelColumn": "AW",
    "group": "Слот Факт (Фактический слот)",
    "subgroup": null,
    "label": "Причина смещения слота (Факт от Бюджета)",
    "path": "Слот Факт (Фактический слот) / Причина смещения слота (Факт от Бюджета)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "C-check",
    "type": "string",
    "availability": "available",
    "source": "EventSlotDeviation.SHIFT_VS_BUDGET",
    "formula": null,
    "sortOrder": 49
  },
  {
    "key": "primary.ax",
    "excelColumn": "AX",
    "group": "Плановая трудоемкость WP согласно MPS",
    "subgroup": null,
    "label": "ME",
    "path": "Плановая трудоемкость WP согласно MPS / ME",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 50
  },
  {
    "key": "primary.ay",
    "excelColumn": "AY",
    "group": "Плановая трудоемкость WP согласно MPS",
    "subgroup": null,
    "label": "AV",
    "path": "Плановая трудоемкость WP согласно MPS / AV",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 51
  },
  {
    "key": "primary.az",
    "excelColumn": "AZ",
    "group": "Плановая трудоемкость WP согласно MPS",
    "subgroup": null,
    "label": "INT",
    "path": "Плановая трудоемкость WP согласно MPS / INT",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 52
  },
  {
    "key": "primary.ba",
    "excelColumn": "BA",
    "group": "Плановая трудоемкость WP согласно MPS",
    "subgroup": null,
    "label": "NDT",
    "path": "Плановая трудоемкость WP согласно MPS / NDT",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 53
  },
  {
    "key": "primary.bb",
    "excelColumn": "BB",
    "group": "Плановая трудоемкость WP согласно MPS",
    "subgroup": null,
    "label": "SHOP",
    "path": "Плановая трудоемкость WP согласно MPS / SHOP",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 54
  },
  {
    "key": "primary.bc",
    "excelColumn": "BC",
    "group": "Плановая трудоемкость WP согласно MPS",
    "subgroup": null,
    "label": "CabRep",
    "path": "Плановая трудоемкость WP согласно MPS / CabRep",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 55
  },
  {
    "key": "primary.bd",
    "excelColumn": "BD",
    "group": "Плановая трудоемкость WP согласно MPS",
    "subgroup": null,
    "label": "Сумма План (ч/ч)",
    "path": "Плановая трудоемкость WP согласно MPS / Сумма План (ч/ч)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(AX7:BC7)",
    "sortOrder": 56
  },
  {
    "key": "primary.be",
    "excelColumn": "BE",
    "group": "Плановая трудоемкость WP согласно MPS",
    "subgroup": null,
    "label": "Выработка в сутки (План)",
    "path": "Плановая трудоемкость WP согласно MPS / Выработка в сутки (План)",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "BD7/AB7",
    "sortOrder": 57
  },
  {
    "key": "primary.bf",
    "excelColumn": "BF",
    "group": "Фактическая трудоемкость WP (завершенное)",
    "subgroup": null,
    "label": "ME",
    "path": "Фактическая трудоемкость WP (завершенное) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 58
  },
  {
    "key": "primary.bg",
    "excelColumn": "BG",
    "group": "Фактическая трудоемкость WP (завершенное)",
    "subgroup": null,
    "label": "AV",
    "path": "Фактическая трудоемкость WP (завершенное) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 59
  },
  {
    "key": "primary.bh",
    "excelColumn": "BH",
    "group": "Фактическая трудоемкость WP (завершенное)",
    "subgroup": null,
    "label": "INT",
    "path": "Фактическая трудоемкость WP (завершенное) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 60
  },
  {
    "key": "primary.bi",
    "excelColumn": "BI",
    "group": "Фактическая трудоемкость WP (завершенное)",
    "subgroup": null,
    "label": "NDT",
    "path": "Фактическая трудоемкость WP (завершенное) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 61
  },
  {
    "key": "primary.bj",
    "excelColumn": "BJ",
    "group": "Фактическая трудоемкость WP (завершенное)",
    "subgroup": null,
    "label": "SHOP",
    "path": "Фактическая трудоемкость WP (завершенное) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 62
  },
  {
    "key": "primary.bk",
    "excelColumn": "BK",
    "group": "Фактическая трудоемкость WP (завершенное)",
    "subgroup": null,
    "label": "CabRep",
    "path": "Фактическая трудоемкость WP (завершенное) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "ALL",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 63
  },
  {
    "key": "primary.bl",
    "excelColumn": "BL",
    "group": "Фактическая трудоемкость WP (завершенное)",
    "subgroup": null,
    "label": "Сумма Факт (ч/ч)",
    "path": "Фактическая трудоемкость WP (завершенное) / Сумма Факт (ч/ч)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BF7:BK7)",
    "sortOrder": 64
  },
  {
    "key": "primary.bm",
    "excelColumn": "BM",
    "group": "Фактическая трудоемкость WP (завершенное)",
    "subgroup": null,
    "label": "Выработка в сутки (Факт)",
    "path": "Фактическая трудоемкость WP (завершенное) / Выработка в сутки (Факт)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "BL7/AO7",
    "sortOrder": 65
  },
  {
    "key": "primary.bn",
    "excelColumn": "BN",
    "group": "Фактическая трудоемкость WP (завершенное)",
    "subgroup": null,
    "label": "Отклонение от Сумма План (ч/ч)",
    "path": "Фактическая трудоемкость WP (завершенное) / Отклонение от Сумма План (ч/ч)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "ALL",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "BD7-BL7",
    "sortOrder": 66
  },
  {
    "key": "primary.bo",
    "excelColumn": "BO",
    "group": "Фиксированная стоимость WP (План)",
    "subgroup": null,
    "label": "ME",
    "path": "Фиксированная стоимость WP (План) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 67
  },
  {
    "key": "primary.bp",
    "excelColumn": "BP",
    "group": "Фиксированная стоимость WP (План)",
    "subgroup": null,
    "label": "AV",
    "path": "Фиксированная стоимость WP (План) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 68
  },
  {
    "key": "primary.bq",
    "excelColumn": "BQ",
    "group": "Фиксированная стоимость WP (План)",
    "subgroup": null,
    "label": "INT",
    "path": "Фиксированная стоимость WP (План) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 69
  },
  {
    "key": "primary.br",
    "excelColumn": "BR",
    "group": "Фиксированная стоимость WP (План)",
    "subgroup": null,
    "label": "NDT",
    "path": "Фиксированная стоимость WP (План) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 70
  },
  {
    "key": "primary.bs",
    "excelColumn": "BS",
    "group": "Фиксированная стоимость WP (План)",
    "subgroup": null,
    "label": "SHOP",
    "path": "Фиксированная стоимость WP (План) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 71
  },
  {
    "key": "primary.bt",
    "excelColumn": "BT",
    "group": "Фиксированная стоимость WP (План)",
    "subgroup": null,
    "label": "CabRep",
    "path": "Фиксированная стоимость WP (План) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 72
  },
  {
    "key": "primary.bu",
    "excelColumn": "BU",
    "group": "Фиксированная стоимость WP (План)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "Фиксированная стоимость WP (План) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BO7:BT7)",
    "sortOrder": 73
  },
  {
    "key": "primary.bv",
    "excelColumn": "BV",
    "group": "T&M (План)",
    "subgroup": null,
    "label": "ME",
    "path": "T&M (План) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 74
  },
  {
    "key": "primary.bw",
    "excelColumn": "BW",
    "group": "T&M (План)",
    "subgroup": null,
    "label": "AV",
    "path": "T&M (План) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 75
  },
  {
    "key": "primary.bx",
    "excelColumn": "BX",
    "group": "T&M (План)",
    "subgroup": null,
    "label": "INT",
    "path": "T&M (План) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 76
  },
  {
    "key": "primary.by",
    "excelColumn": "BY",
    "group": "T&M (План)",
    "subgroup": null,
    "label": "NDT",
    "path": "T&M (План) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 77
  },
  {
    "key": "primary.bz",
    "excelColumn": "BZ",
    "group": "T&M (План)",
    "subgroup": null,
    "label": "SHOP",
    "path": "T&M (План) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 78
  },
  {
    "key": "primary.ca",
    "excelColumn": "CA",
    "group": "T&M (План)",
    "subgroup": null,
    "label": "CabRep",
    "path": "T&M (План) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 79
  },
  {
    "key": "primary.cb",
    "excelColumn": "CB",
    "group": "T&M (План)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "T&M (План) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BV7:CA7)",
    "sortOrder": 80
  },
  {
    "key": "primary.cc",
    "excelColumn": "CC",
    "group": "Трудоемкость на обеспечение доступа (План)",
    "subgroup": null,
    "label": "ME",
    "path": "Трудоемкость на обеспечение доступа (План) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 81
  },
  {
    "key": "primary.cd",
    "excelColumn": "CD",
    "group": "Трудоемкость на обеспечение доступа (План)",
    "subgroup": null,
    "label": "AV",
    "path": "Трудоемкость на обеспечение доступа (План) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 82
  },
  {
    "key": "primary.ce",
    "excelColumn": "CE",
    "group": "Трудоемкость на обеспечение доступа (План)",
    "subgroup": null,
    "label": "INT",
    "path": "Трудоемкость на обеспечение доступа (План) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 83
  },
  {
    "key": "primary.cf",
    "excelColumn": "CF",
    "group": "Трудоемкость на обеспечение доступа (План)",
    "subgroup": null,
    "label": "NDT",
    "path": "Трудоемкость на обеспечение доступа (План) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 84
  },
  {
    "key": "primary.cg",
    "excelColumn": "CG",
    "group": "Трудоемкость на обеспечение доступа (План)",
    "subgroup": null,
    "label": "SHOP",
    "path": "Трудоемкость на обеспечение доступа (План) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 85
  },
  {
    "key": "primary.ch",
    "excelColumn": "CH",
    "group": "Трудоемкость на обеспечение доступа (План)",
    "subgroup": null,
    "label": "CabRep",
    "path": "Трудоемкость на обеспечение доступа (План) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 86
  },
  {
    "key": "primary.ci",
    "excelColumn": "CI",
    "group": "Трудоемкость на обеспечение доступа (План)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "Трудоемкость на обеспечение доступа (План) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(CC7:CH7)",
    "sortOrder": 87
  },
  {
    "key": "primary.cj",
    "excelColumn": "CJ",
    "group": "Трудоемкость на NRC (План)",
    "subgroup": null,
    "label": "ME",
    "path": "Трудоемкость на NRC (План) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 88
  },
  {
    "key": "primary.ck",
    "excelColumn": "CK",
    "group": "Трудоемкость на NRC (План)",
    "subgroup": null,
    "label": "AV",
    "path": "Трудоемкость на NRC (План) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 89
  },
  {
    "key": "primary.cl",
    "excelColumn": "CL",
    "group": "Трудоемкость на NRC (План)",
    "subgroup": null,
    "label": "INT",
    "path": "Трудоемкость на NRC (План) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 90
  },
  {
    "key": "primary.cm",
    "excelColumn": "CM",
    "group": "Трудоемкость на NRC (План)",
    "subgroup": null,
    "label": "NDT",
    "path": "Трудоемкость на NRC (План) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 91
  },
  {
    "key": "primary.cn",
    "excelColumn": "CN",
    "group": "Трудоемкость на NRC (План)",
    "subgroup": null,
    "label": "SHOP",
    "path": "Трудоемкость на NRC (План) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 92
  },
  {
    "key": "primary.co",
    "excelColumn": "CO",
    "group": "Трудоемкость на NRC (План)",
    "subgroup": null,
    "label": "CabRep",
    "path": "Трудоемкость на NRC (План) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 93
  },
  {
    "key": "primary.cp",
    "excelColumn": "CP",
    "group": "Трудоемкость на NRC (План)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "Трудоемкость на NRC (План) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(CJ7:CO7)",
    "sortOrder": 94
  },
  {
    "key": "primary.cq",
    "excelColumn": "CQ",
    "group": "% NRC (План)",
    "subgroup": null,
    "label": "% NRC (План)",
    "path": "% NRC (План)",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 95
  },
  {
    "key": "primary.cr",
    "excelColumn": "CR",
    "group": "Трудоемкость на ADD (План)",
    "subgroup": null,
    "label": "ME",
    "path": "Трудоемкость на ADD (План) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 96
  },
  {
    "key": "primary.cs",
    "excelColumn": "CS",
    "group": "Трудоемкость на ADD (План)",
    "subgroup": null,
    "label": "AV",
    "path": "Трудоемкость на ADD (План) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 97
  },
  {
    "key": "primary.ct",
    "excelColumn": "CT",
    "group": "Трудоемкость на ADD (План)",
    "subgroup": null,
    "label": "INT",
    "path": "Трудоемкость на ADD (План) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 98
  },
  {
    "key": "primary.cu",
    "excelColumn": "CU",
    "group": "Трудоемкость на ADD (План)",
    "subgroup": null,
    "label": "NDT",
    "path": "Трудоемкость на ADD (План) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 99
  },
  {
    "key": "primary.cv",
    "excelColumn": "CV",
    "group": "Трудоемкость на ADD (План)",
    "subgroup": null,
    "label": "SHOP",
    "path": "Трудоемкость на ADD (План) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 100
  },
  {
    "key": "primary.cw",
    "excelColumn": "CW",
    "group": "Трудоемкость на ADD (План)",
    "subgroup": null,
    "label": "CabRep",
    "path": "Трудоемкость на ADD (План) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 101
  },
  {
    "key": "primary.cx",
    "excelColumn": "CX",
    "group": "Трудоемкость на ADD (План)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "Трудоемкость на ADD (План) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(CR7:CW7)",
    "sortOrder": 102
  },
  {
    "key": "primary.cy",
    "excelColumn": "CY",
    "group": "Mhrs ADD (План)",
    "subgroup": null,
    "label": "Mhrs ADD (План)",
    "path": "Mhrs ADD (План)",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 103
  },
  {
    "key": "primary.cz",
    "excelColumn": "CZ",
    "group": "Total (План)",
    "subgroup": null,
    "label": "Total (План)",
    "path": "Total (План)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BU7,CB7,CI7,CP7,CX7)",
    "sortOrder": 104
  },
  {
    "key": "primary.da",
    "excelColumn": "DA",
    "group": "Расчет ИТП (ME)",
    "subgroup": null,
    "label": "Расчет ИТП (ME)",
    "path": "Расчет ИТП (ME)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BO7,BV7,CC7,CJ7,CR7)",
    "sortOrder": 105
  },
  {
    "key": "primary.db",
    "excelColumn": "DB",
    "group": "Расчет ИТП (AV)",
    "subgroup": null,
    "label": "Расчет ИТП (AV)",
    "path": "Расчет ИТП (AV)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BP7,BW7,CD7,CK7,CS7)",
    "sortOrder": 106
  },
  {
    "key": "primary.dc",
    "excelColumn": "DC",
    "group": "Расчет ИТП (ME+AV)",
    "subgroup": null,
    "label": "Расчет ИТП (ME+AV)",
    "path": "Расчет ИТП (ME+AV)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DA7:DB7)",
    "sortOrder": 107
  },
  {
    "key": "primary.dd",
    "excelColumn": "DD",
    "group": "Расчет ИТП (INT)",
    "subgroup": null,
    "label": "Расчет ИТП (INT)",
    "path": "Расчет ИТП (INT)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BQ7,BX7,CE7,CL7,CT7)",
    "sortOrder": 108
  },
  {
    "key": "primary.de",
    "excelColumn": "DE",
    "group": "Расчет ИТП (NDT)",
    "subgroup": null,
    "label": "Расчет ИТП (NDT)",
    "path": "Расчет ИТП (NDT)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BR7,BY7,CF7,CM7,CU7)",
    "sortOrder": 109
  },
  {
    "key": "primary.df",
    "excelColumn": "DF",
    "group": "Расчет ИТП (SHOP)",
    "subgroup": null,
    "label": "Расчет ИТП (SHOP)",
    "path": "Расчет ИТП (SHOP)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BS7,BZ7,CG7,CN7,CV7)",
    "sortOrder": 110
  },
  {
    "key": "primary.dg",
    "excelColumn": "DG",
    "group": "Расчет ИТП (CabRep)",
    "subgroup": null,
    "label": "Расчет ИТП (CabRep)",
    "path": "Расчет ИТП (CabRep)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(BT7,CA7,CH7,CO7,CW7)",
    "sortOrder": 111
  },
  {
    "key": "primary.dh",
    "excelColumn": "DH",
    "group": "Фиксированная стоимость (Факт)",
    "subgroup": null,
    "label": "ME",
    "path": "Фиксированная стоимость (Факт) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 112
  },
  {
    "key": "primary.di",
    "excelColumn": "DI",
    "group": "Фиксированная стоимость (Факт)",
    "subgroup": null,
    "label": "AV",
    "path": "Фиксированная стоимость (Факт) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 113
  },
  {
    "key": "primary.dj",
    "excelColumn": "DJ",
    "group": "Фиксированная стоимость (Факт)",
    "subgroup": null,
    "label": "INT",
    "path": "Фиксированная стоимость (Факт) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 114
  },
  {
    "key": "primary.dk",
    "excelColumn": "DK",
    "group": "Фиксированная стоимость (Факт)",
    "subgroup": null,
    "label": "NDT",
    "path": "Фиксированная стоимость (Факт) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 115
  },
  {
    "key": "primary.dl",
    "excelColumn": "DL",
    "group": "Фиксированная стоимость (Факт)",
    "subgroup": null,
    "label": "SHOP",
    "path": "Фиксированная стоимость (Факт) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 116
  },
  {
    "key": "primary.dm",
    "excelColumn": "DM",
    "group": "Фиксированная стоимость (Факт)",
    "subgroup": null,
    "label": "CabRep",
    "path": "Фиксированная стоимость (Факт) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 117
  },
  {
    "key": "primary.dn",
    "excelColumn": "DN",
    "group": "Фиксированная стоимость (Факт)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "Фиксированная стоимость (Факт) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DH7:DM7)",
    "sortOrder": 118
  },
  {
    "key": "primary.do",
    "excelColumn": "DO",
    "group": "T&M (Факт)",
    "subgroup": null,
    "label": "ME",
    "path": "T&M (Факт) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 119
  },
  {
    "key": "primary.dp",
    "excelColumn": "DP",
    "group": "T&M (Факт)",
    "subgroup": null,
    "label": "AV",
    "path": "T&M (Факт) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 120
  },
  {
    "key": "primary.dq",
    "excelColumn": "DQ",
    "group": "T&M (Факт)",
    "subgroup": null,
    "label": "INT",
    "path": "T&M (Факт) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 121
  },
  {
    "key": "primary.dr",
    "excelColumn": "DR",
    "group": "T&M (Факт)",
    "subgroup": null,
    "label": "NDT",
    "path": "T&M (Факт) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 122
  },
  {
    "key": "primary.ds",
    "excelColumn": "DS",
    "group": "T&M (Факт)",
    "subgroup": null,
    "label": "SHOP",
    "path": "T&M (Факт) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 123
  },
  {
    "key": "primary.dt",
    "excelColumn": "DT",
    "group": "T&M (Факт)",
    "subgroup": null,
    "label": "CabRep",
    "path": "T&M (Факт) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 124
  },
  {
    "key": "primary.du",
    "excelColumn": "DU",
    "group": "T&M (Факт)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "T&M (Факт) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DO7:DT7)",
    "sortOrder": 125
  },
  {
    "key": "primary.dv",
    "excelColumn": "DV",
    "group": "Фактические данные NRC (Факт)",
    "subgroup": null,
    "label": "ME",
    "path": "Фактические данные NRC (Факт) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 126
  },
  {
    "key": "primary.dw",
    "excelColumn": "DW",
    "group": "Фактические данные NRC (Факт)",
    "subgroup": null,
    "label": "AV",
    "path": "Фактические данные NRC (Факт) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 127
  },
  {
    "key": "primary.dx",
    "excelColumn": "DX",
    "group": "Фактические данные NRC (Факт)",
    "subgroup": null,
    "label": "INT",
    "path": "Фактические данные NRC (Факт) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 128
  },
  {
    "key": "primary.dy",
    "excelColumn": "DY",
    "group": "Фактические данные NRC (Факт)",
    "subgroup": null,
    "label": "NDT",
    "path": "Фактические данные NRC (Факт) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 129
  },
  {
    "key": "primary.dz",
    "excelColumn": "DZ",
    "group": "Фактические данные NRC (Факт)",
    "subgroup": null,
    "label": "SHOP",
    "path": "Фактические данные NRC (Факт) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 130
  },
  {
    "key": "primary.ea",
    "excelColumn": "EA",
    "group": "Фактические данные NRC (Факт)",
    "subgroup": null,
    "label": "CabRep",
    "path": "Фактические данные NRC (Факт) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 131
  },
  {
    "key": "primary.eb",
    "excelColumn": "EB",
    "group": "Фактические данные NRC (Факт)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "Фактические данные NRC (Факт) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DV7:EA7)",
    "sortOrder": 132
  },
  {
    "key": "primary.ec",
    "excelColumn": "EC",
    "group": "% NRC (Факт)",
    "subgroup": null,
    "label": "% NRC (Факт)",
    "path": "% NRC (Факт)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "EB7/SUM(DN7,DU7,EJ7)*100%",
    "sortOrder": 133
  },
  {
    "key": "primary.ed",
    "excelColumn": "ED",
    "group": "Фактические данные ADD (Факт)",
    "subgroup": null,
    "label": "ME",
    "path": "Фактические данные ADD (Факт) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 134
  },
  {
    "key": "primary.ee",
    "excelColumn": "EE",
    "group": "Фактические данные ADD (Факт)",
    "subgroup": null,
    "label": "AV",
    "path": "Фактические данные ADD (Факт) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 135
  },
  {
    "key": "primary.ef",
    "excelColumn": "EF",
    "group": "Фактические данные ADD (Факт)",
    "subgroup": null,
    "label": "INT",
    "path": "Фактические данные ADD (Факт) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 136
  },
  {
    "key": "primary.eg",
    "excelColumn": "EG",
    "group": "Фактические данные ADD (Факт)",
    "subgroup": null,
    "label": "NDT",
    "path": "Фактические данные ADD (Факт) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 137
  },
  {
    "key": "primary.eh",
    "excelColumn": "EH",
    "group": "Фактические данные ADD (Факт)",
    "subgroup": null,
    "label": "SHOP",
    "path": "Фактические данные ADD (Факт) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 138
  },
  {
    "key": "primary.ei",
    "excelColumn": "EI",
    "group": "Фактические данные ADD (Факт)",
    "subgroup": null,
    "label": "CabRep",
    "path": "Фактические данные ADD (Факт) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 139
  },
  {
    "key": "primary.ej",
    "excelColumn": "EJ",
    "group": "Фактические данные ADD (Факт)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "Фактические данные ADD (Факт) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(ED7:EI7)",
    "sortOrder": 140
  },
  {
    "key": "primary.ek",
    "excelColumn": "EK",
    "group": "Mhrs ADD (Факт)",
    "subgroup": null,
    "label": "Mhrs ADD (Факт)",
    "path": "Mhrs ADD (Факт)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "EJ7",
    "sortOrder": 141
  },
  {
    "key": "primary.el",
    "excelColumn": "EL",
    "group": "Total (Факт)",
    "subgroup": null,
    "label": "Total (Факт)",
    "path": "Total (Факт)",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DN7,DU7,EB7,EJ7)",
    "sortOrder": 142
  },
  {
    "key": "primary.em",
    "excelColumn": "EM",
    "group": "Отклонение",
    "subgroup": null,
    "label": "%NRC",
    "path": "Отклонение / %NRC",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "CQ7-EC7",
    "sortOrder": 143
  },
  {
    "key": "primary.en",
    "excelColumn": "EN",
    "group": "Отклонение",
    "subgroup": null,
    "label": "ADD Mhrs",
    "path": "Отклонение / ADD Mhrs",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "CY7-EK7",
    "sortOrder": 144
  },
  {
    "key": "primary.eo",
    "excelColumn": "EO",
    "group": "Отклонение",
    "subgroup": null,
    "label": "Total Mhrs",
    "path": "Отклонение / Total Mhrs",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "CZ7-EL7",
    "sortOrder": 145
  },
  {
    "key": "primary.ep",
    "excelColumn": "EP",
    "group": "Квартал",
    "subgroup": null,
    "label": "Квартал",
    "path": "Квартал",
    "owner": "ОПП",
    "fillMode": "COMPUTED",
    "applicability": "All",
    "type": "string",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "CONCATENATE(ROUNDUP((MONTH(AM7)/3),0),\"кв.\",YEAR(AM7))",
    "sortOrder": 146
  },
  {
    "key": "primary.eq",
    "excelColumn": "EQ",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "ME+AV",
    "label": "MAIN",
    "path": "Фактическая трудоемкость по подразделениям / ME+AV / MAIN",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DH7:DI7,DO7:DP7,ED7:EE7)",
    "sortOrder": 147
  },
  {
    "key": "primary.er",
    "excelColumn": "ER",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "ME+AV",
    "label": "NRC",
    "path": "Фактическая трудоемкость по подразделениям / ME+AV / NRC",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DV7:DW7)",
    "sortOrder": 148
  },
  {
    "key": "primary.es",
    "excelColumn": "ES",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "ME+AV",
    "label": "Прирост %",
    "path": "Фактическая трудоемкость по подразделениям / ME+AV / Прирост %",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(EQ7:ER7)/SUM(AX7:AY7)-1",
    "sortOrder": 149
  },
  {
    "key": "primary.et",
    "excelColumn": "ET",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "INT",
    "label": "MAIN",
    "path": "Фактическая трудоемкость по подразделениям / INT / MAIN",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DJ7,DQ7,EF7)",
    "sortOrder": 150
  },
  {
    "key": "primary.eu",
    "excelColumn": "EU",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "INT",
    "label": "NRC",
    "path": "Фактическая трудоемкость по подразделениям / INT / NRC",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DX7)",
    "sortOrder": 151
  },
  {
    "key": "primary.ev",
    "excelColumn": "EV",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "INT",
    "label": "Прирост %",
    "path": "Фактическая трудоемкость по подразделениям / INT / Прирост %",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(ET7:EU7)/SUM(AZ7)-1",
    "sortOrder": 152
  },
  {
    "key": "primary.ew",
    "excelColumn": "EW",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "NDT/BORO",
    "label": "MAIN",
    "path": "Фактическая трудоемкость по подразделениям / NDT/BORO / MAIN",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DK7,DR7,EG7)",
    "sortOrder": 153
  },
  {
    "key": "primary.ex",
    "excelColumn": "EX",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "NDT/BORO",
    "label": "NRC",
    "path": "Фактическая трудоемкость по подразделениям / NDT/BORO / NRC",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DY7)",
    "sortOrder": 154
  },
  {
    "key": "primary.ey",
    "excelColumn": "EY",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "NDT/BORO",
    "label": "Прирост %",
    "path": "Фактическая трудоемкость по подразделениям / NDT/BORO / Прирост %",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(EW7:EX7)/SUM(BA7)-1",
    "sortOrder": 155
  },
  {
    "key": "primary.ez",
    "excelColumn": "EZ",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "SHOP",
    "label": "MAIN",
    "path": "Фактическая трудоемкость по подразделениям / SHOP / MAIN",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DL7,DS7,EH7)",
    "sortOrder": 156
  },
  {
    "key": "primary.fa",
    "excelColumn": "FA",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "SHOP",
    "label": "NRC",
    "path": "Фактическая трудоемкость по подразделениям / SHOP / NRC",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DZ7)",
    "sortOrder": 157
  },
  {
    "key": "primary.fb",
    "excelColumn": "FB",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "SHOP",
    "label": "Прирост %",
    "path": "Фактическая трудоемкость по подразделениям / SHOP / Прирост %",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(EZ7:FA7)/SUM(BB7)-1",
    "sortOrder": 158
  },
  {
    "key": "primary.fc",
    "excelColumn": "FC",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "CabRep",
    "label": "MAIN",
    "path": "Фактическая трудоемкость по подразделениям / CabRep / MAIN",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(DM7,DT7,EI7)",
    "sortOrder": 159
  },
  {
    "key": "primary.fd",
    "excelColumn": "FD",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "CabRep",
    "label": "NRC",
    "path": "Фактическая трудоемкость по подразделениям / CabRep / NRC",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(EA7)",
    "sortOrder": 160
  },
  {
    "key": "primary.fe",
    "excelColumn": "FE",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "CabRep",
    "label": "Прирост %",
    "path": "Фактическая трудоемкость по подразделениям / CabRep / Прирост %",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(FC7:FD7)/SUM(BC7)-1",
    "sortOrder": 161
  },
  {
    "key": "primary.ff",
    "excelColumn": "FF",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Выработка в смену по подразделениям (Факт)",
    "label": "ME+AV",
    "path": "Фактическая трудоемкость по подразделениям / Выработка в смену по подразделениям (Факт) / ME+AV",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(EQ7:ER7)/AO7",
    "sortOrder": 162
  },
  {
    "key": "primary.fg",
    "excelColumn": "FG",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Выработка в смену по подразделениям (Факт)",
    "label": "INT",
    "path": "Фактическая трудоемкость по подразделениям / Выработка в смену по подразделениям (Факт) / INT",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(ET7:EU7)/AO7",
    "sortOrder": 163
  },
  {
    "key": "primary.fh",
    "excelColumn": "FH",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Выработка в смену по подразделениям (Факт)",
    "label": "NDT",
    "path": "Фактическая трудоемкость по подразделениям / Выработка в смену по подразделениям (Факт) / NDT",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(EW7:EX7)/AO7",
    "sortOrder": 164
  },
  {
    "key": "primary.fi",
    "excelColumn": "FI",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Выработка в смену по подразделениям (Факт)",
    "label": "SHOP",
    "path": "Фактическая трудоемкость по подразделениям / Выработка в смену по подразделениям (Факт) / SHOP",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(EZ7:FA7)/AO7",
    "sortOrder": 165
  },
  {
    "key": "primary.fj",
    "excelColumn": "FJ",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Выработка в смену по подразделениям (Факт)",
    "label": "CabRep",
    "path": "Фактическая трудоемкость по подразделениям / Выработка в смену по подразделениям (Факт) / CabRep",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(FC7:FD7)/AO7",
    "sortOrder": 166
  },
  {
    "key": "primary.fk",
    "excelColumn": "FK",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Выработка в смену по подразделениям (Факт)",
    "label": "TOTAL",
    "path": "Фактическая трудоемкость по подразделениям / Выработка в смену по подразделениям (Факт) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(FF7:FJ7)",
    "sortOrder": 167
  },
  {
    "key": "primary.fl",
    "excelColumn": "FL",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Трудоемкость (ч/ч) (Факт)",
    "label": "Без учета SHOP",
    "path": "Фактическая трудоемкость по подразделениям / Трудоемкость (ч/ч) (Факт) / Без учета SHOP",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(EQ7:ER7,ET7:EU7,EW7:EX7,FC7:FD7)",
    "sortOrder": 168
  },
  {
    "key": "primary.fm",
    "excelColumn": "FM",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Трудоемкость (ч/ч) (Факт)",
    "label": "С учетом SHOP",
    "path": "Фактическая трудоемкость по подразделениям / Трудоемкость (ч/ч) (Факт) / С учетом SHOP",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(EQ7:ER7,ET7:EU7,EW7:EX7,EZ7:FA7,FC7:FD7)",
    "sortOrder": 169
  },
  {
    "key": "primary.fn",
    "excelColumn": "FN",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Прирост % (Факт)",
    "label": "Без учета SHOP",
    "path": "Фактическая трудоемкость по подразделениям / Прирост % (Факт) / Без учета SHOP",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "FL7/SUM(AX7,AY7,AZ7,BA7,BC7)-1",
    "sortOrder": 170
  },
  {
    "key": "primary.fo",
    "excelColumn": "FO",
    "group": "Фактическая трудоемкость по подразделениям",
    "subgroup": "Прирост % (Факт)",
    "label": "С учетом SHOP",
    "path": "Фактическая трудоемкость по подразделениям / Прирост % (Факт) / С учетом SHOP",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "percent",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "FM7/SUM(BD7)-1",
    "sortOrder": 171
  },
  {
    "key": "primary.fp",
    "excelColumn": "FP",
    "group": "Трудоемкость (Бюджет)",
    "subgroup": null,
    "label": "ME",
    "path": "Трудоемкость (Бюджет) / ME",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 172
  },
  {
    "key": "primary.fq",
    "excelColumn": "FQ",
    "group": "Трудоемкость (Бюджет)",
    "subgroup": null,
    "label": "AV",
    "path": "Трудоемкость (Бюджет) / AV",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 173
  },
  {
    "key": "primary.fr",
    "excelColumn": "FR",
    "group": "Трудоемкость (Бюджет)",
    "subgroup": null,
    "label": "INT",
    "path": "Трудоемкость (Бюджет) / INT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 174
  },
  {
    "key": "primary.fs",
    "excelColumn": "FS",
    "group": "Трудоемкость (Бюджет)",
    "subgroup": null,
    "label": "NDT",
    "path": "Трудоемкость (Бюджет) / NDT",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 175
  },
  {
    "key": "primary.ft",
    "excelColumn": "FT",
    "group": "Трудоемкость (Бюджет)",
    "subgroup": null,
    "label": "SHOP",
    "path": "Трудоемкость (Бюджет) / SHOP",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 176
  },
  {
    "key": "primary.fu",
    "excelColumn": "FU",
    "group": "Трудоемкость (Бюджет)",
    "subgroup": null,
    "label": "CabRep",
    "path": "Трудоемкость (Бюджет) / CabRep",
    "owner": "ГАПД",
    "fillMode": "MANUAL",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "available",
    "source": "EventReportMetric / EventReportScalar",
    "formula": null,
    "sortOrder": 177
  },
  {
    "key": "primary.fv",
    "excelColumn": "FV",
    "group": "Трудоемкость (Бюджет)",
    "subgroup": null,
    "label": "TOTAL",
    "path": "Трудоемкость (Бюджет) / TOTAL",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "SUM(FP7:FU7)",
    "sortOrder": 178
  },
  {
    "key": "primary.fw",
    "excelColumn": "FW",
    "group": "Трудоемкость (Бюджет)",
    "subgroup": null,
    "label": "Отклонение (от Total Факт) ч/ч",
    "path": "Трудоемкость (Бюджет) / Отклонение (от Total Факт) ч/ч",
    "owner": "ГАПД",
    "fillMode": "COMPUTED",
    "applicability": "С-Сheck",
    "type": "number",
    "availability": "computed",
    "source": "primaryTable formulaEngine",
    "formula": "FV7-EL7",
    "sortOrder": 179
  },
  {
    "key": "primary.fx",
    "excelColumn": "FX",
    "group": "Трудоемкость (Бюджет)",
    "subgroup": null,
    "label": "Номер WP (Факт)",
    "path": "Трудоемкость (Бюджет) / Номер WP (Факт)",
    "owner": "ОПП",
    "fillMode": "MANUAL",
    "applicability": "All",
    "type": "string",
    "availability": "available",
    "source": "EventPrimaryExtension.wpNumberFact",
    "formula": null,
    "sortOrder": 180
  },
  {
    "key": "primary.fy",
    "excelColumn": "FY",
    "group": "Скользящий график ПТО",
    "subgroup": null,
    "label": "Ключ",
    "path": "Скользящий график ПТО / Ключ",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "string",
    "availability": "available",
    "source": "EventPtoRollingEntry.externalKey",
    "formula": null,
    "sortOrder": 181
  },
  {
    "key": "primary.fz",
    "excelColumn": "FZ",
    "group": "Скользящий график ПТО",
    "subgroup": null,
    "label": "Статус",
    "path": "Скользящий график ПТО / Статус",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "string",
    "availability": "available",
    "source": "EventPtoRollingEntry.status",
    "formula": null,
    "sortOrder": 182
  },
  {
    "key": "primary.ga",
    "excelColumn": "GA",
    "group": "Скользящий график ПТО",
    "subgroup": null,
    "label": "1_КИПП часы",
    "path": "Скользящий график ПТО / 1_КИПП часы",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "string",
    "availability": "available",
    "source": "EventPtoRollingEntry.kippHours",
    "formula": null,
    "sortOrder": 183
  },
  {
    "key": "primary.gb",
    "excelColumn": "GB",
    "group": "Скользящий график ПТО",
    "subgroup": null,
    "label": "Трудоемкость итого",
    "path": "Скользящий график ПТО / Трудоемкость итого",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "string",
    "availability": "available",
    "source": "EventPtoRollingEntry.laborTotal",
    "formula": null,
    "sortOrder": 184
  },
  {
    "key": "primary.gc",
    "excelColumn": "GC",
    "group": "Скользящий график ПТО",
    "subgroup": null,
    "label": "Сумма",
    "path": "Скользящий график ПТО / Сумма",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "string",
    "availability": "available",
    "source": "EventPtoRollingEntry.amount",
    "formula": null,
    "sortOrder": 185
  },
  {
    "key": "primary.gd",
    "excelColumn": "GD",
    "group": "Скользящий график ПТО",
    "subgroup": null,
    "label": "Категория",
    "path": "Скользящий график ПТО / Категория",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "string",
    "availability": "available",
    "source": "EventPtoRollingEntry.category",
    "formula": null,
    "sortOrder": 186
  },
  {
    "key": "primary.ge",
    "excelColumn": "GE",
    "group": "Скользящий график ПТО",
    "subgroup": null,
    "label": "Комментарии",
    "path": "Скользящий график ПТО / Комментарии",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "string",
    "availability": "available",
    "source": "EventPtoRollingEntry.comments",
    "formula": null,
    "sortOrder": 187
  },
  {
    "key": "primary.gf",
    "excelColumn": "GF",
    "group": "Анализ по A-CH",
    "subgroup": null,
    "label": "Статус",
    "path": "Анализ по A-CH / Статус",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "string",
    "availability": "available",
    "source": "EventACheckAnalysis.status",
    "formula": null,
    "sortOrder": 188
  },
  {
    "key": "primary.gg",
    "excelColumn": "GG",
    "group": "Анализ по A-CH",
    "subgroup": null,
    "label": "Количество",
    "path": "Анализ по A-CH / Количество",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "integer",
    "availability": "available",
    "source": "EventACheckAnalysis.quantity",
    "formula": null,
    "sortOrder": 189
  },
  {
    "key": "primary.gh",
    "excelColumn": "GH",
    "group": "Анализ по A-CH",
    "subgroup": null,
    "label": "Программа (Факт/План)",
    "path": "Анализ по A-CH / Программа (Факт/План)",
    "owner": "ГАПД",
    "fillMode": "UNSPECIFIED",
    "applicability": null,
    "type": "string",
    "availability": "available",
    "source": "EventACheckAnalysis.program",
    "formula": null,
    "sortOrder": 190
  }
];

export const PRIMARY_TABLE_COLUMN_BY_KEY = new Map(PRIMARY_TABLE_COLUMNS.map((column) => [column.key, column]));
